// <auto-generated />
using System;
using Accipiter.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Accipiter.Infrastructure.Migrations
{
    [DbContext(typeof(AccipitersDbContext))]
    partial class AccipitersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Accipiter.Infrastructure.Persistence.ExecutedTradeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ActualOutputAmountUSDC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ActualProfitUSDC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("InputAmountUSDC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Reverted")
                        .HasColumnType("bit");

                    b.Property<string>("TxSignature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExecutedTrades");
                });

            modelBuilder.Entity("Accipiter.Infrastructure.Persistence.OpportunityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuyDex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("DiscoveredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("EstimatedOutputAmountUSDC")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("EstimatedProfitUSDC")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("InputAmountUSDC")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("InputToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellDex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StrategyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiscoveredAt");

                    b.HasIndex("Status");

                    b.ToTable("Opportunities");
                });

            modelBuilder.Entity("Accipiter.Infrastructure.Persistence.SimulationRunLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("NetPnLUSDC")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("TotalLossUSDC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalOpportunitiesFound")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalProfitUSDC")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("SimulationRuns");
                });

            modelBuilder.Entity("Accipiter.Infrastructure.Persistence.SimulationTradeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("InputAmountUSDC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("OutputAmountUSDC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProfitUSDC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("SimulatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SimulationRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("WouldHaveReverted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("SimulationRunId");

                    b.ToTable("SimulationTrades");
                });

            modelBuilder.Entity("Accipiter.Infrastructure.Persistence.WalletSnapshotLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("SolBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalValueUSDC")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("UsdcBalance")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt");

                    b.ToTable("WalletSnapshots");
                });

            modelBuilder.Entity("Accipiter.Infrastructure.Persistence.SimulationTradeLog", b =>
                {
                    b.HasOne("Accipiter.Infrastructure.Persistence.SimulationRunLog", "SimulationRun")
                        .WithMany("Trades")
                        .HasForeignKey("SimulationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulationRun");
                });

            modelBuilder.Entity("Accipiter.Infrastructure.Persistence.SimulationRunLog", b =>
                {
                    b.Navigation("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
